#!/usr/bin/env python3
"""
CLIP Directional Similarity — Metric Calculator (SigLIP 2 Giant)
=================================================================

Computes the directional similarity between RAG-enhanced and base prompts
using embeddings from **google/siglip2-giant-opt-patch16-384** (2 B params,
ViT-Giant/16 @ 384 px, trained on WebLI).

Metric (StyleGAN-NADA / Gal et al., 2021)
------------------------------------------

    delta_T   = norm( embed_text(enhanced) − embed_text(base) )
    delta_I_i = norm( embed_image(enhanced_i) − embed_image(base_i) )
    score_i   = dot( delta_T, delta_I_i )          ∈ [−1, +1]
    S_dir     = mean( score_i )

    +1 → visual shift perfectly mirrors textual shift
     0 → orthogonal (no correlation)
    −1 → opposite directions

Assumes images have already been generated by generate_images.py.
Images are expected at:
    outputs/directional_similarity/<model>/row_<ID>/base_seed<SEED:05d>.png
    outputs/directional_similarity/<model>/row_<ID>/enhanced_seed<SEED:05d>.png

Model
-----
    google/siglip2-giant-opt-patch16-384
    • ViT-Giant/16, image size 384×384
    • 1152-dim embeddings
    • Loaded in float16 → ~4 GB on one A100; fits easily alongside Qwen on
      a separate GPU (or in a separate process when Qwen has released VRAM).

Usage
-----
    # evaluate all rows using cached images
    python calculate_metric.py

    # specify a different image directory or results output dir
    python calculate_metric.py --image-dir outputs/directional_similarity --results-dir results

    # run metric on CUDA device 1
    python calculate_metric.py --device cuda:1

    # choose which enhanced prompt variant matches the generated images
    python calculate_metric.py --enhanced-idx 0

CLI flags
---------
  --csv             prompts CSV  (default: inputs/prompts.csv)
  --image-dir       root folder with generated images (default: outputs/directional_similarity)
  --results-dir     where to write JSON + CSV results (default: results)
  --device          torch device for SigLIP2 (default: cuda:0 if available)
  --model           which model's images to evaluate (default: qwen)
  --enhanced-idx    which enhanced prompt variant was used for generation (default: 0)
  --batch-size      images per forward pass through SigLIP2 (default: 8)
"""

from __future__ import annotations

import argparse
import ast
import csv
import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

import torch
import torch.nn.functional as F
from PIL import Image
from transformers import AutoModel, AutoProcessor

sys.path.insert(0, str(Path(__file__).resolve().parent))
from logger import get_logger, log_section, log_subsection, log_timer
from generate_images import MODEL_CONFIGS, DEFAULT_MODEL

logger = get_logger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────

SIGLIP2_MODEL_ID: str  = "google/siglip2-giant-opt-patch16-384"
IMAGE_OUTPUT_DIR: Path = Path("outputs") / "directional_similarity"
RESULTS_DIR:      Path = Path("results")
INPUT_CSV:        Path = Path("inputs") / "prompts.csv"
DEFAULT_BATCH:    int  = 8     # images per SigLIP2 forward pass

# SigLIP2 text context length (model was trained with 64 tokens)
SIGLIP2_MAX_TEXT_LENGTH: int = 64


# ─────────────────────────────────────────────────────────────────────────────
# Model — singleton loader
# ─────────────────────────────────────────────────────────────────────────────

_model:     Optional[AutoModel]     = None
_processor: Optional[AutoProcessor] = None
_device:    Optional[torch.device]  = None


def load_siglip2(
    device: Optional[torch.device] = None,
) -> tuple[AutoModel, AutoProcessor, torch.device]:
    """
    Load SigLIP 2 Giant once; return cached objects on subsequent calls.

    The model is loaded in float16 to keep VRAM usage low (~4 GB on one A100),
    leaving the second GPU free for image generation (if running concurrently).
    """
    global _model, _processor, _device

    if _model is not None:
        assert _processor is not None and _device is not None
        return _model, _processor, _device

    if device is None:
        device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

    log_section(logger, f"Loading SigLIP 2 Giant  ·  {SIGLIP2_MODEL_ID}")
    logger.info("Target device  : %s", device)
    logger.info(
        "Spec           : ViT-Giant/16 @ 384px  |  1152-dim embeddings  "
        "|  2 B params  |  float16  |  WebLI pre-training"
    )

    with log_timer(logger, "SigLIP 2 Giant  processor + model load"):
        processor = AutoProcessor.from_pretrained(SIGLIP2_MODEL_ID)
        model = AutoModel.from_pretrained(
            SIGLIP2_MODEL_ID,
            torch_dtype=torch.float16 if device.type == "cuda" else torch.float32,
        ).to(device)
        model.eval()

    n_params = sum(p.numel() for p in model.parameters()) / 1e9
    logger.info("Loaded  %.2f B parameters", n_params)

    if device.type == "cuda":
        used  = torch.cuda.memory_allocated(device) / 1024**3
        total = torch.cuda.get_device_properties(device).total_memory / 1024**3
        logger.info(
            "VRAM after model load : %.2f / %.2f GB  (%s)", used, total, device
        )

    _model, _processor, _device = model, processor, device
    return model, processor, device


# ─────────────────────────────────────────────────────────────────────────────
# Embedding helpers
# ─────────────────────────────────────────────────────────────────────────────

@torch.no_grad()
def get_text_embedding(
    model:     AutoModel,
    processor: AutoProcessor,
    text:      str,
    device:    torch.device,
) -> torch.Tensor:
    """
    Encode *text* → L2-normalised float32 embedding of shape (D,).

    SigLIP 2 uses sigmoid loss (not softmax) and does not automatically
    normalise its features, so explicit L2 normalisation is applied here
    before returning.  Truncates to the model's 64-token context limit.
    """
    inputs = processor(
        text=[text],
        return_tensors="pt",
        padding="max_length",
        max_length=SIGLIP2_MAX_TEXT_LENGTH,
        truncation=True,
    ).to(device)

    features = model.get_text_features(**inputs)        # (1, D)  float16
    if not isinstance(features, torch.Tensor):          # some versions return ModelOutput
        features = features.pooler_output
    features = features.float()                         # upcast before norm
    features = F.normalize(features, dim=-1)            # unit sphere
    return features.squeeze(0)                          # (D,)


@torch.no_grad()
def get_image_embedding(
    model:     AutoModel,
    processor: AutoProcessor,
    image:     Image.Image,
    device:    torch.device,
) -> torch.Tensor:
    """
    Encode a PIL *image* → L2-normalised float32 embedding of shape (D,).

    SigLIP 2's processor resizes / center-crops to 384×384 internally.
    """
    inputs = processor(
        images=image,
        return_tensors="pt",
    ).to(device)

    features = model.get_image_features(**inputs)       # (1, D)  float16
    if not isinstance(features, torch.Tensor):          # some versions return ModelOutput
        features = features.pooler_output
    features = features.float()
    features = F.normalize(features, dim=-1)
    return features.squeeze(0)                          # (D,)


@torch.no_grad()
def get_image_embeddings_batch(
    model:      AutoModel,
    processor:  AutoProcessor,
    images:     list[Image.Image],
    device:     torch.device,
    batch_size: int = DEFAULT_BATCH,
) -> torch.Tensor:
    """
    Encode a list of PIL images in batches.

    Returns a (N, D) float32 tensor of L2-normalised embeddings.
    Batching avoids repeated CPU→GPU transfers and saturates the GPU better
    than one-by-one calls.
    """
    all_embs: list[torch.Tensor] = []

    for start in range(0, len(images), batch_size):
        batch = images[start : start + batch_size]
        inputs = processor(images=batch, return_tensors="pt").to(device)
        features = model.get_image_features(**inputs)   # (B, D)
        if not isinstance(features, torch.Tensor):      # some versions return ModelOutput
            features = features.pooler_output
        features = features.float()
        features = F.normalize(features, dim=-1)
        all_embs.append(features)

    return torch.cat(all_embs, dim=0)                   # (N, D)


# ─────────────────────────────────────────────────────────────────────────────
# Core metric function
# ─────────────────────────────────────────────────────────────────────────────

def compute_directional_similarity(
    base_prompt:          str,
    enhanced_prompt:      str,
    base_image_paths:     list[Path],
    enhanced_image_paths: list[Path],
    model:                AutoModel,
    processor:            AutoProcessor,
    device:               torch.device,
    batch_size:           int = DEFAULT_BATCH,
) -> tuple[list[float], float]:
    """
    Compute CLIP directional similarity for one prompt pair.

    Parameters
    ----------
    base_prompt / enhanced_prompt   : Text prompts (already validated).
    base_image_paths / enhanced_image_paths : Paired image paths (same seeds).
    model / processor / device      : Loaded SigLIP 2 objects.
    batch_size                       : Images per GPU forward pass.

    Returns
    -------
    (per_pair_scores, average_score)
    """
    if len(base_image_paths) != len(enhanced_image_paths):
        raise ValueError(
            f"base ({len(base_image_paths)}) and enhanced "
            f"({len(enhanced_image_paths)}) path lists must be the same length."
        )
    if not base_image_paths:
        raise ValueError("Image path lists must not be empty.")

    # ── Text direction vector ──────────────────────────────────────────────
    with log_timer(logger, "text direction encoding"):
        emb_base_txt = get_text_embedding(model, processor, base_prompt,     device)
        emb_enh_txt  = get_text_embedding(model, processor, enhanced_prompt, device)

        delta_T      = emb_enh_txt - emb_base_txt                      # (D,)
        delta_T_norm = F.normalize(delta_T.unsqueeze(0), dim=-1).squeeze(0)

    logger.debug(
        "delta_T  raw_norm=%.4f  (0 ≈ identical texts in embedding space)",
        delta_T.norm().item(),
    )

    # ── Load all images ────────────────────────────────────────────────────
    n = len(base_image_paths)
    base_pil     = [Image.open(p).convert("RGB") for p in base_image_paths]
    enhanced_pil = [Image.open(p).convert("RGB") for p in enhanced_image_paths]

    # ── Image embeddings (batched) ─────────────────────────────────────────
    with log_timer(logger, f"image embedding batch  ({n} base + {n} enhanced)"):
        embs_base = get_image_embeddings_batch(
            model, processor, base_pil, device, batch_size
        )  # (N, D)
        embs_enh  = get_image_embeddings_batch(
            model, processor, enhanced_pil, device, batch_size
        )  # (N, D)

    # ── Per-pair cosine similarities ───────────────────────────────────────
    delta_I      = embs_enh - embs_base                               # (N, D)
    delta_I_norm = F.normalize(delta_I, dim=-1)                       # (N, D)

    # Broadcast delta_T_norm (D,) → dot with each row of delta_I_norm
    scores_t = (delta_I_norm @ delta_T_norm).tolist()                 # list[float]

    per_pair_scores: list[float] = scores_t
    avg_score: float             = sum(per_pair_scores) / len(per_pair_scores)

    for i, (bp, ep, s) in enumerate(
        zip(base_image_paths, enhanced_image_paths, per_pair_scores)
    ):
        logger.debug(
            "  pair %02d/%02d  score=%+.4f  base=%-30s  enh=%s",
            i + 1, n, s, Path(bp).name, Path(ep).name,
        )

    logger.info(
        "  directional similarity  avg=%+.4f  min=%+.4f  max=%+.4f  n=%d",
        avg_score,
        min(per_pair_scores),
        max(per_pair_scores),
        n,
    )
    return per_pair_scores, avg_score


# ─────────────────────────────────────────────────────────────────────────────
# CSV helpers
# ─────────────────────────────────────────────────────────────────────────────

def _parse_enhanced_prompts(raw: str) -> list[str]:
    raw = raw.strip()
    for parser in (json.loads, ast.literal_eval):
        try:
            parsed = parser(raw)  # type: ignore[operator]
            if isinstance(parsed, list):
                return [str(p) for p in parsed]
            if isinstance(parsed, str):
                return [parsed]
        except (json.JSONDecodeError, ValueError, SyntaxError):
            continue
    logger.warning("Could not parse enhanced_prompts as list; using raw string.")
    return [raw]


def load_prompt_pairs(csv_path: Path) -> list[dict]:
    rows: list[dict] = []
    with open(csv_path, newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            rows.append(
                {
                    "row_id":           str(row.get("__row_id__", row.get("row_id", "?"))),
                    "base_prompt":      row["generic_prompt"].strip(),
                    "enhanced_prompts": _parse_enhanced_prompts(row["enhanced_prompts"]),
                }
            )
    logger.info("Loaded %d prompt pairs from %s", len(rows), csv_path)
    return rows


# ─────────────────────────────────────────────────────────────────────────────
# Main metric pipeline
# ─────────────────────────────────────────────────────────────────────────────

def calculate_directional_similarity(
    csv_path:         Path                  = INPUT_CSV,
    image_dir:        Path                  = IMAGE_OUTPUT_DIR,
    results_dir:      Path                  = RESULTS_DIR,
    device:           Optional[torch.device] = None,
    model_name:       str                   = DEFAULT_MODEL,
    enhanced_idx:     int                   = 0,
    batch_size:       int                   = DEFAULT_BATCH,
) -> list[dict]:
    """
    Compute directional similarity for all rows in the prompts CSV using
    SigLIP 2 Giant embeddings.

    Assumes images have already been generated under *image_dir* by
    generate_images.py (or run_pipeline.py).

    Parameters
    ----------
    csv_path     : Prompts CSV (must contain generic_prompt + enhanced_prompts).
    image_dir    : Root directory where generated images live.
    results_dir  : Folder for result JSON + CSV files. A model-named
                   subdirectory is created automatically (e.g. results/qwen/).
    device       : Torch device for SigLIP 2. Auto-selected if None.
    model_name   : Model subdirectory inside image_dir (e.g. 'qwen', 'flux-dev').
    enhanced_idx : Which enhanced prompt variant to load from the CSV.
    batch_size   : Images per SigLIP 2 forward pass.

    Returns
    -------
    List of per-row result dicts with keys:
        row_id, base_prompt, enhanced_prompt, num_pairs,
        per_pair_scores, avg_score
    """
    log_section(logger, "Directional Similarity  ·  SigLIP 2 Giant")

    results_dir = results_dir / model_name          # e.g. results/qwen/

    logger.info("Model          : %s", SIGLIP2_MODEL_ID)
    logger.info("Gen model      : %s", model_name)
    logger.info("Image dir      : %s", image_dir)
    logger.info("Results dir    : %s", results_dir)
    logger.info("Enhanced idx   : %d", enhanced_idx)
    logger.info("Batch size     : %d", batch_size)

    results_dir.mkdir(parents=True, exist_ok=True)

    # ── Load model ONCE before iterating rows ──────────────────────────────
    model, processor, dev = load_siglip2(device)

    # ── Load prompts ──────────────────────────────────────────────────────
    prompt_pairs = load_prompt_pairs(csv_path)
    all_results:  list[dict] = []

    for entry in prompt_pairs:
        row_id         = entry["row_id"]
        base_prompt    = entry["base_prompt"]
        enh_list       = entry["enhanced_prompts"]

        if not enh_list:
            logger.warning("Row %s has no enhanced prompts — skipping.", row_id)
            continue

        idx             = min(enhanced_idx, len(enh_list) - 1)
        enhanced_prompt = enh_list[idx]
        row_dir         = image_dir / model_name / f"row_{row_id}"

        log_subsection(logger, f"Row {row_id}")
        logger.info("  Base     : %.100s", base_prompt)
        logger.info("  Enhanced : %.100s", enhanced_prompt)

        # ── Discover image pairs ───────────────────────────────────────────
        base_paths = sorted(row_dir.glob("base_seed*.png"))
        enh_paths  = sorted(row_dir.glob("enhanced_seed*.png"))

        if not base_paths or not enh_paths:
            logger.warning(
                "No images found for row %s at %s — skipping. "
                "Run generate_images.py first.",
                row_id, row_dir,
            )
            continue

        if len(base_paths) != len(enh_paths):
            n = min(len(base_paths), len(enh_paths))
            logger.warning(
                "Unequal image counts (base=%d, enh=%d) for row %s — "
                "using first %d pairs.",
                len(base_paths), len(enh_paths), row_id, n,
            )
            base_paths, enh_paths = base_paths[:n], enh_paths[:n]

        logger.info("  Image pairs : %d", len(base_paths))

        # ── Compute metric ─────────────────────────────────────────────────
        with log_timer(logger, f"directional similarity  row {row_id}"):
            per_pair_scores, avg_score = compute_directional_similarity(
                base_prompt          = base_prompt,
                enhanced_prompt      = enhanced_prompt,
                base_image_paths     = base_paths,
                enhanced_image_paths = enh_paths,
                model                = model,
                processor            = processor,
                device               = dev,
                batch_size           = batch_size,
            )

        result = {
            "row_id":           row_id,
            "base_prompt":      base_prompt,
            "enhanced_prompt":  enhanced_prompt,
            "num_pairs":        len(per_pair_scores),
            "per_pair_scores":  [round(s, 6) for s in per_pair_scores],
            "avg_score":        round(avg_score, 6),
        }
        all_results.append(result)
        logger.info(
            "  ✔ Row %-5s  avg_directional_similarity = %+.4f",
            row_id, avg_score,
        )

    # ── Save ──────────────────────────────────────────────────────────────
    _save_results(all_results, results_dir)

    if all_results:
        overall = sum(r["avg_score"] for r in all_results) / len(all_results)
        log_section(
            logger,
            f"DONE  |  {len(all_results)} rows  "
            f"|  overall avg directional similarity = {overall:+.4f}",
        )
    else:
        log_section(logger, "DONE  |  no rows evaluated (check image paths)")

    return all_results


# ─────────────────────────────────────────────────────────────────────────────
# Results persistence
# ─────────────────────────────────────────────────────────────────────────────

def _save_results(results: list[dict], results_dir: Path) -> None:
    """Write results to a timestamped JSON file and a flat CSV file."""
    if not results:
        logger.warning("No results to save.")
        return

    ts        = datetime.now().strftime("%Y%m%d_%H%M%S")
    json_path = results_dir / f"directional_similarity_{ts}.json"
    csv_path  = results_dir / f"directional_similarity_{ts}.csv"

    with open(json_path, "w", encoding="utf-8") as fh:
        json.dump(results, fh, indent=2, ensure_ascii=False)
    logger.info("Results (JSON) → %s", json_path)

    fieldnames = [
        "row_id", "base_prompt", "enhanced_prompt",
        "num_pairs", "avg_score", "per_pair_scores",
    ]
    with open(csv_path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        for row in results:
            out = dict(row)
            out["per_pair_scores"] = json.dumps(out["per_pair_scores"])
            writer.writerow(out)
    logger.info("Results (CSV)  → %s", csv_path)


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description=(
            "Compute CLIP directional similarity using SigLIP 2 Giant "
            "on pre-generated images."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--csv",          type=Path, default=INPUT_CSV,
                   metavar="PATH",   help="Input prompts CSV.")
    p.add_argument("--image-dir",    type=Path, default=IMAGE_OUTPUT_DIR,
                   metavar="DIR",    help="Root directory containing generated images.")
    p.add_argument("--results-dir",  type=Path, default=RESULTS_DIR,
                   metavar="DIR",    help="Output directory for results.")
    p.add_argument("--device",       type=str,  default=None,
                   metavar="DEVICE", help="Torch device (e.g. cuda:0, cuda:1, cpu).")
    p.add_argument("--model",         type=str,  default=DEFAULT_MODEL,
                   choices=list(MODEL_CONFIGS),
                   help="Which model's generated images to evaluate.")
    p.add_argument("--enhanced-idx", type=int,  default=0,
                   metavar="IDX",    help="Enhanced prompt variant index (0-indexed).")
    p.add_argument("--batch-size",   type=int,  default=DEFAULT_BATCH,
                   metavar="N",      help="Images per SigLIP2 forward pass.")
    return p


def main() -> None:
    args   = _build_parser().parse_args()
    device = torch.device(args.device) if args.device else None
    calculate_directional_similarity(
        csv_path     = args.csv,
        image_dir    = args.image_dir,
        results_dir  = args.results_dir,
        device       = device,
        model_name   = args.model,
        enhanced_idx = args.enhanced_idx,
        batch_size   = args.batch_size,
    )


if __name__ == "__main__":
    main()
